name: alumni-management-system
description: A combined deployment of the Alumni Management System with both client and server components
version: 1.0.0

variables:
  - name: MONGODB_URI
    description: MongoDB connection string
    default: mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
    required: true
  
  - name: DATABASE_NAME
    description: MongoDB database name
    default: alumni_management
    required: true
  
  - name: JWT_SECRET_KEY
    description: Secret key for JWT token generation
    default: your_super_secret_key_for_jwt_tokens
    required: true

services:
  - name: alumni-system
    type: container
    image: ${REGISTRY}/alumni-management-system:latest
    ports:
      - port: 5000
        published: 80
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - name: model-storage
        mountPath: /opt/models

volumes:
  - name: model-storage
    size: 1Gi
