version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ynodev/alumni-server:latest
    container_name: alumni-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
      - DATABASE_NAME=alumni_management
      - JWT_SECRET_KEY=your_super_secret_key_for_jwt_tokens
    networks:
      - alumni-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: ynodev/alumni-client:latest
    container_name: alumni-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - alumni-network

networks:
  alumni-network:
    driver: bridge
