services:
  # Backend API service
  - type: web
    name: alumni-api
    env: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && python run.py
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
      - key: DATABASE_NAME
        value: alumni_management
      - key: JWT_SECRET_KEY
        value: your_super_secret_key_for_jwt_tokens
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: 3.8.0

  # Frontend static site
  - type: static
    name: alumni-client
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://alumni-api.onrender.com