services:
  # Fixed Combined Alumni Management System service
  - type: web
    name: alumni-management-system
    env: docker
    dockerCommand: /app/start.sh
    image: docker.io/ynodev/alumni-combined:fixed
    region: ohio  # Change to your preferred region if needed
    plan: starter  # Change to your preferred plan if needed
    healthCheckPath: /api/health
    envVars:
      # Database Configuration
      - key: MONGODB_URI
        value: mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
      - key: DATABASE_NAME
        value: alumni_management
      
      # Security Configuration
      - key: JWT_SECRET_KEY
        value: your_super_secret_key_for_jwt_tokens
      
      # Server Configuration
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
