services:
  # Combined service (frontend + backend)
  - type: web
    name: alumni-combined
    env: docker
    dockerfilePath: ./Dockerfile.combined
    dockerContext: .
    plan: free
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
      - key: DATABASE_NAME
        value: alumni_management
      - key: JWT_SECRET_KEY
        value: your_super_secret_key_for_jwt_tokens
      - key: PORT
        value: 5000
