services:
  - type: web
    name: alumni-management-system
    env: python
    region: ohio
    buildCommand: |
      pip install -r requirements.txt
      cd client && npm install && npm run build
      cd ../server && npm install
      chmod +x ../start.sh
    startCommand: bash ./start.sh
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
      - key: DATABASE_NAME
        value: alumni_management
      - key: JWT_SECRET_KEY
        value: your_super_secret_key_for_jwt_tokens
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.8.0