services:
  # Combined Alumni Management System service
  - type: web
    name: alumni-management-system
    env: docker
    dockerCommand: /app/start.sh
    image: docker.io/ynodev/alumni-combined:latest
    region: ohio  # Change to your preferred region: singapore, frankfurt, ohio, oregon, sydney
    plan: starter  # Change to your preferred plan: starter, standard, pro, etc.
    healthCheckPath: /api/health
    envVars:
      # Database Configuration
      - key: MONGODB_URI
        value: mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
      - key: DATABASE_NAME
        value: alumni_management
      
      # Security Configuration
      - key: JWT_SECRET_KEY
        value: your_super_secret_key_for_jwt_tokens
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: 86400  # 24 hours in seconds
      
      # Server Configuration
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      
      # CORS Configuration
      - key: CORS_ALLOW_ORIGINS
        value: "*"  # In production, you might want to restrict this
      
      # Application Configuration
      - key: APP_NAME
        value: "Alumni Management System"
      - key: ADMIN_EMAIL
        value: admin@alumni.edu
      - key: ADMIN_PASSWORD
        value: admin123  # Change this in production
      
      # Model Configuration
      - key: MODEL_STORAGE_TYPE
        value: mongodb  # Options: mongodb, filesystem
      - key: MODEL_COLLECTION_PREFIX
        value: model_
      
      # Logging Configuration
      - key: LOG_LEVEL
        value: info  # Options: debug, info, warning, error, critical
      
      # Performance Configuration
      - key: GUNICORN_WORKERS
        value: 2
      - key: GUNICORN_THREADS
        value: 4
      - key: GUNICORN_TIMEOUT
        value: 120
      
      # Feature Flags
      - key: ENABLE_MODEL_TRAINING
        value: true
      - key: ENABLE_ANALYTICS
        value: true
      - key: ENABLE_SAMPLE_GENERATION
        value: true
      
      # Render-specific Configuration
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: alumni-management-system
          type: web
          property: url
      
      # Optional: Email Configuration (if you implement email features)
      - key: SMTP_SERVER
        value: ""
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: ""
      - key: SMTP_PASSWORD
        value: ""
      - key: EMAIL_FROM
        value: "Alumni Management <noreply@alumni.edu>"
