services:
  # Backend API service
  - type: web
    name: alumni-management-api
    env: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://dsilva:7DaXRzRoueTBa3a5@alumnimanagement.f10hpn9.mongodb.net/?retryWrites=true&w=majority&appName=AlumniManagement
      - key: DATABASE_NAME
        value: alumni_management
      - key: JWT_SECRET_KEY
        value: your_super_secret_key_for_jwt_tokens
      - key: PORT
        value: 5000
      - key: CORS_ALLOW_ORIGINS
        value: "https://alumni-client-three.vercel.app"
